import type {
  EmotionPreset,
  ScenePreset,
  SynthesisSettings,
  VoicePreset,
} from "./types";

/**
 * Voice catalog — Indonesian voices across genders, ages and styles.
 * Each voice is a fixed "cast member": the same voice id always renders with
 * the same characteristics, so multi-scene projects stay consistent.
 */
export const VOICES: VoicePreset[] = [
  {
    id: "arka",
    name: "Arka",
    gender: "male",
    style: "deep",
    age: "adult",
    tagline: "Narasi deep & profesional untuk dokumenter dan iklan premium.",
    traits: { basePitch: 96, rate: 158, brightness: 0.55, breathiness: 0.08, energy: 0.5 },
  },
  {
    id: "bagas",
    name: "Bagas",
    gender: "male",
    style: "energetic",
    age: "young",
    tagline: "Energik dan cepat — pas untuk TikTok, reels, dan iklan muda.",
    traits: { basePitch: 122, rate: 190, brightness: 0.82, breathiness: 0.05, energy: 0.85 },
  },
  {
    id: "sari",
    name: "Sari",
    gender: "female",
    style: "professional",
    age: "adult",
    tagline: "Wanita profesional yang tegas dan meyakinkan untuk korporat.",
    traits: { basePitch: 200, rate: 168, brightness: 0.72, breathiness: 0.1, energy: 0.55 },
  },
  {
    id: "dewi",
    name: "Dewi",
    gender: "female",
    style: "casual",
    age: "young",
    tagline: "Ramah dan santai — suara vlog, sosial media, dan obrolan.",
    traits: { basePitch: 226, rate: 180, brightness: 0.86, breathiness: 0.12, energy: 0.7 },
  },
  {
    id: "rendra",
    name: "Rendra",
    gender: "male",
    style: "storyteller",
    age: "adult",
    tagline: "Hangat dan ekspresif — pendongeng untuk podcast dan dongeng.",
    traits: { basePitch: 110, rate: 150, brightness: 0.6, breathiness: 0.14, energy: 0.6 },
  },
  {
    id: "maya",
    name: "Maya",
    gender: "female",
    style: "storyteller",
    age: "adult",
    tagline: "Ekspresif dan hidup — audiobook, narasi, dan sinematik.",
    traits: { basePitch: 192, rate: 160, brightness: 0.68, breathiness: 0.15, energy: 0.65 },
  },
  {
    id: "prabu",
    name: "Prabu",
    gender: "male",
    style: "deep",
    age: "mature",
    tagline: "Dalam, berwibawa, sinematik — trailer dan brand premium.",
    traits: { basePitch: 84, rate: 140, brightness: 0.45, breathiness: 0.1, energy: 0.55 },
  },
  {
    id: "laras",
    name: "Laras",
    gender: "female",
    style: "warm",
    age: "adult",
    tagline: "Lembut dan menenangkan — meditasi, wellness, dokumenter alam.",
    traits: { basePitch: 182, rate: 145, brightness: 0.6, breathiness: 0.16, energy: 0.35 },
  },
  {
    id: "doni",
    name: "Doni",
    gender: "male",
    style: "casual",
    age: "adult",
    tagline: "Santai seperti ngobrol — podcast dan konten edukasi.",
    traits: { basePitch: 116, rate: 165, brightness: 0.65, breathiness: 0.12, energy: 0.55 },
  },
  {
    id: "kevin",
    name: "Kevin",
    gender: "male",
    style: "ad",
    age: "young",
    tagline: "Bersemangat dan persuasif — iklan produk dan promo.",
    traits: { basePitch: 128, rate: 195, brightness: 0.85, breathiness: 0.05, energy: 0.9 },
  },
  {
    id: "citra",
    name: "Citra",
    gender: "female",
    style: "professional",
    age: "adult",
    tagline: "Wanita muda yang tajam — iklan TVC dan promo brand.",
    traits: { basePitch: 212, rate: 176, brightness: 0.8, breathiness: 0.08, energy: 0.75 },
  },
  {
    id: "anggun",
    name: "Anggun",
    gender: "female",
    style: "warm",
    age: "mature",
    tagline: "Elegan dan eksklusif — luxury brand dan narasi kelas atas.",
    traits: { basePitch: 176, rate: 150, brightness: 0.55, breathiness: 0.14, energy: 0.45 },
  },
];

export const getVoice = (id: string): VoicePreset =>
  VOICES.find((v) => v.id === id) ?? VOICES[0];

/**
 * Emotion catalog — these shift pitch, rate, brightness and energy of the
 * chosen voice while keeping its identity intact.
 */
export const EMOTIONS: EmotionPreset[] = [
  {
    id: "natural",
    name: "Natural",
    description: "Netral, apa adanya.",
    pitchDelta: 0,
    rateDelta: 1,
    brightnessDelta: 0,
    energyDelta: 0,
    breathDelta: 0,
    contour: "neutral",
  },
  {
    id: "happy",
    name: "Happy",
    description: "Ceria dan ringan.",
    pitchDelta: 2,
    rateDelta: 1.05,
    brightnessDelta: 0.15,
    energyDelta: 0.15,
    breathDelta: 0.02,
    contour: "lifted",
  },
  {
    id: "excited",
    name: "Excited",
    description: "Semangat tinggi, cepat.",
    pitchDelta: 3.5,
    rateDelta: 1.18,
    brightnessDelta: 0.2,
    energyDelta: 0.3,
    breathDelta: 0,
    contour: "lifted",
  },
  {
    id: "calm",
    name: "Calm",
    description: "Tenang dan stabil.",
    pitchDelta: -1.5,
    rateDelta: 0.92,
    brightnessDelta: -0.1,
    energyDelta: -0.2,
    breathDelta: 0.04,
    contour: "calm",
  },
  {
    id: "friendly",
    name: "Friendly",
    description: "Akrab dan hangat.",
    pitchDelta: 1,
    rateDelta: 1.03,
    brightnessDelta: 0.08,
    energyDelta: 0.05,
    breathDelta: 0.03,
    contour: "neutral",
  },
  {
    id: "serious",
    name: "Serious",
    description: "Tegas dan berwibawa.",
    pitchDelta: -1,
    rateDelta: 0.97,
    brightnessDelta: -0.05,
    energyDelta: -0.05,
    breathDelta: -0.02,
    contour: "neutral",
  },
  {
    id: "dramatic",
    name: "Dramatic",
    description: "Tegang, penuh jeda.",
    pitchDelta: 1.5,
    rateDelta: 0.85,
    brightnessDelta: 0.05,
    energyDelta: 0.2,
    breathDelta: 0.06,
    contour: "dramatic",
  },
  {
    id: "persuasive",
    name: "Persuasive",
    description: "Meyakinkan, menekan.",
    pitchDelta: 1.2,
    rateDelta: 1.06,
    brightnessDelta: 0.12,
    energyDelta: 0.15,
    breathDelta: 0,
    contour: "persuasive",
  },
  {
    id: "professional",
    name: "Professional",
    description: "Formal dan presisi.",
    pitchDelta: 0,
    rateDelta: 0.98,
    brightnessDelta: 0,
    energyDelta: -0.02,
    breathDelta: -0.02,
    contour: "neutral",
  },
  {
    id: "sedih",
    name: "Sedih",
    description: "Sendu dan pelan.",
    pitchDelta: -2.2,
    rateDelta: 0.88,
    brightnessDelta: -0.12,
    energyDelta: -0.25,
    breathDelta: 0.08,
    contour: "calm",
  },
  {
    id: "misterius",
    name: "Misterius",
    description: "Berbisik, penuh rahasia.",
    pitchDelta: -0.5,
    rateDelta: 0.9,
    brightnessDelta: -0.15,
    energyDelta: -0.1,
    breathDelta: 0.1,
    contour: "dramatic",
  },
];

export const getEmotion = (id: string): EmotionPreset =>
  EMOTIONS.find((e) => e.id === id) ?? EMOTIONS[0];

/**
 * Scene presets — one-click starting points tuned per use case.
 */
export const SCENE_PRESETS: ScenePreset[] = [
  {
    id: "advertisement",
    name: "Advertisement",
    description: "Cepat, hidup, persuasif.",
    emotionId: "persuasive",
    speed: 1.15,
    pitch: 6,
    intonation: 70,
    volume: 88,
    pause: 25,
    suggestedVoiceId: "kevin",
  },
  {
    id: "tiktok",
    name: "TikTok",
    description: "Energik, ngebut, catchy.",
    emotionId: "excited",
    speed: 1.25,
    pitch: 10,
    intonation: 80,
    volume: 92,
    pause: 10,
    suggestedVoiceId: "bagas",
  },
  {
    id: "youtube",
    name: "YouTube",
    description: "Ramah dan mengalir.",
    emotionId: "friendly",
    speed: 1.05,
    pitch: 2,
    intonation: 60,
    volume: 85,
    pause: 40,
    suggestedVoiceId: "doni",
  },
  {
    id: "storytelling",
    name: "Storytelling",
    description: "Ekspresif dengan jeda dramatis.",
    emotionId: "dramatic",
    speed: 0.9,
    pitch: 4,
    intonation: 85,
    volume: 85,
    pause: 70,
    suggestedVoiceId: "rendra",
  },
  {
    id: "documentary",
    name: "Documentary",
    description: "Berwibawa dan informatif.",
    emotionId: "professional",
    speed: 0.95,
    pitch: -2,
    intonation: 50,
    volume: 82,
    pause: 55,
    suggestedVoiceId: "arka",
  },
  {
    id: "cinematic",
    name: "Cinematic",
    description: "Sinematik, dalam, epik.",
    emotionId: "dramatic",
    speed: 0.85,
    pitch: -4,
    intonation: 90,
    volume: 88,
    pause: 75,
    suggestedVoiceId: "prabu",
  },
  {
    id: "luxury",
    name: "Luxury",
    description: "Elegan, tenang, eksklusif.",
    emotionId: "calm",
    speed: 0.92,
    pitch: 0,
    intonation: 45,
    volume: 80,
    pause: 60,
    suggestedVoiceId: "anggun",
  },
];

export const getScenePreset = (id: string): ScenePreset | undefined =>
  SCENE_PRESETS.find((p) => p.id === id);

/** Neutral starting settings. */
export const DEFAULT_SETTINGS: SynthesisSettings = {
  voiceId: "sari",
  emotionId: "natural",
  intonation: 55,
  pitch: 0,
  speed: 1,
  volume: 85,
  pause: 35,
  autoDirect: true,
};
